# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2007-2017
  project: Connector Services
  version: 3.1
  release: 3.1.0
  latex_documents:
  - - Index
    - svconnector.tex
    - Connector Services
    - Francois Suter
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
...
